#!/bin/sh
#
# mk_fish_default
#
# Makes fish shell the default shell choice for an account.
#
# (c) Jamie Culpon 2019. See LICENCE for more details.
sh=$(sh)
env=$(usr/bin/env)

sh -s /usr/local/bin/fish
